{
 "title": "reBOOT LAN",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "WAN Download",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "Mbits",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT last(\"ifInOctets_rate\") FROM \"ports\" WHERE (\"hostname\" = 'lab-fcx-stk.mfi.lab' AND \"ifName\" = 'ethernet1/1/1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 8 /1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-upstairs-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet1/1/1" }
     ]
    }
   ]
  },
  {
   "title": "WAN Upload",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "Mbits",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT last(\"ifOutOctets_rate\") * 8 /1000000 FROM \"ports\" WHERE (\"hostname\" = 'lab-wan-agg-fcx.mfi.lab' AND \"ifName\" = 'ethernet1/1/1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifOutOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 8 /1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-upstairs-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet1/1/1" }
     ]
    }
   ]
  },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "content": "<center>\r\n  <font size=\"+3\">Food/WIFI/Games Info - <a href=\"http://reboot.com/\">reboot.com</a>\r\n  </font>\r\n</center>"
  },
  {
   "title": "Firewall CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processors",
     "query": "SELECT last(\"ifInOctets_rate\") * 8 /1000000 FROM \"ports\" WHERE (\"hostname\" = 'lab-wan-agg-fcx.mfi.lab' AND \"ifName\" = 'ethernet1/1/1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "pfsense.mfi.lab" },
      { "condition": "AND", "key": "processor_type", "operator": "=", "value": "hr" }
     ]
    }
   ]
  },
  {
   "title": "Server CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processors",
     "query": "SELECT last(\"ifInOctets_rate\") * 8 /1000000 FROM \"ports\" WHERE (\"hostname\" = 'lab-wan-agg-fcx.mfi.lab' AND \"ifName\" = 'ethernet1/1/1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "xen-01.mfi.lab" },
      { "condition": "AND", "key": "processor_type", "operator": "=", "value": "hr" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "app",
     "select": [
      [
       { "params": [ "dhcp_active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app_id", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "hostname", "operator": "=", "value": "dhcp.mfi.lab" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wireless-sensor",
     "select": [
      [
       { "params": [ "sensor" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "ap.mfi.lab" },
      { "condition": "AND", "key": "sensor_class", "operator": "=", "value": "clients" }
     ]
    }
   ]
  },
  {
   "title": "DOCSIS WAN (Intertubes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-upstairs-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet1/1/1" }
     ]
    },
    {
     "alias": "Upload Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "select": [
      [
       { "params": [ "ifOutOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-upstairs-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet1/1/1" }
     ]
    }
   ]
  },
  {
   "title": "Firewall CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Firewall Load (pfsense.mfi.lab)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processors",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "pfsense.mfi.lab" },
      { "condition": "AND", "key": "processor_type", "operator": "=", "value": "hr" }
     ]
    }
   ]
  },
  {
   "title": "Server CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Hypervisor #1 Load (XEN-01)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processors",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "xen-01.mfi.lab" },
      { "condition": "AND", "key": "processor_type", "operator": "=", "value": "hr" }
     ]
    },
    {
     "alias": "Hypervisor #2 Load (XEN-02)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processors",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "xen-02.mfi.lab" },
      { "condition": "AND", "key": "processor_type", "operator": "=", "value": "hr" }
     ]
    }
   ]
  },
  {
   "title": "XEN-01 (Main Server)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifOutOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/3\\/1|ethernet2\\/3\\/1)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet2/3/1" }
     ]
    },
    {
     "alias": "Upload Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifInOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/3\\/1|ethernet2\\/3\\/1)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet2/3/1" }
     ]
    }
   ]
  },
  {
   "title": "XEN-02 (Backup Server)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifOutOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/3\\/2|ethernet2\\/3\\/2)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet2/3/1" }
     ]
    },
    {
     "alias": "Upload Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifInOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/3\\/2|ethernet2\\/3\\/2)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet2/3/1" }
     ]
    }
   ]
  },
  {
   "title": "SteamCache Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download (From Valve)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifOutOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/3\\/1|ethernet2\\/3\\/1)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "steamcache.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "eth1" }
     ]
    },
    {
     "alias": "Upload (To Clients)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifOutOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/3\\/1|ethernet2\\/3\\/1)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifOutOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "steamcache.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "eth1" }
     ]
    }
   ]
  },
  {
   "title": "reBOOT WIFI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bps", "label": "Bandwidth" }
   ],
   "targets": [
    {
     "alias": "Download Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "select": [
      [
       { "params": [ "ifOutOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet1/1/1" }
     ]
    },
    {
     "alias": "Upload Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet1/1/1" }
     ]
    },
    {
     "alias": "Connected Devices",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wireless-sensor",
     "select": [
      [
       { "params": [ "sensor" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "ap.mfi.lab" },
      { "condition": "AND", "key": "sensor_class", "operator": "=", "value": "clients" }
     ]
    }
   ]
  },
  {
   "title": "Central Wiring Closet Aggregation Chassis (FCX Stack)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download Activity (From Core)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifOutOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/3\\/3|ethernet2\\/3\\/3)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet2/3/1" }
     ]
    },
    {
     "alias": "Upload Activity (To Core)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifInOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/3\\/3|ethernet2\\/3\\/3)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet2/3/1" }
     ]
    }
   ]
  }
 ]
}