{
 "title": "reBOOT LAN",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "WAN Download",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "Mbits",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"ifInOctets_rate\") * 8 /1000000 FROM \"ports\" WHERE (\"hostname\" = 'lab-wan-agg-fcx.mfi.lab' AND \"ifName\" = 'ethernet1/1/1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WAN Upload",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "Mbits",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"ifOutOctets_rate\") * 8 /1000000 FROM \"ports\" WHERE (\"hostname\" = 'lab-wan-agg-fcx.mfi.lab' AND \"ifName\" = 'ethernet1/1/1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "content": "<center>\r\n  <font size=\"+3\">For This & Food/WIFI Info \r\n  <br>\r\n  Please Visit - <a href=\"http://reboot.com/\">reboot.com</a>\r\n  </font>\r\n</center>"
  },
  {
   "title": "Firewall CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processors",
     "query": "SELECT last(\"ifInOctets_rate\") * 8 /1000000 FROM \"ports\" WHERE (\"hostname\" = 'lab-wan-agg-fcx.mfi.lab' AND \"ifName\" = 'ethernet1/1/1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "pfsense.mfi.lab" },
      { "condition": "AND", "key": "processor_type", "operator": "=", "value": "hr" }
     ]
    }
   ]
  },
  {
   "title": "Server CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processors",
     "query": "SELECT last(\"ifInOctets_rate\") * 8 /1000000 FROM \"ports\" WHERE (\"hostname\" = 'lab-wan-agg-fcx.mfi.lab' AND \"ifName\" = 'ethernet1/1/1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "xen-01.mfi.lab" },
      { "condition": "AND", "key": "processor_type", "operator": "=", "value": "hr" }
     ]
    }
   ]
  },
  {
   "title": "DOCSIS WAN (Intertubes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-wan-agg-fcx.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet1/1/1" }
     ]
    },
    {
     "alias": "Upload Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "select": [
      [
       { "params": [ "ifOutOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-wan-agg-fcx.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet1/1/1" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Firewall Load (pfsense.mfi.lab)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processors",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "pfsense.mfi.lab" },
      { "condition": "AND", "key": "processor_type", "operator": "=", "value": "hr" }
     ]
    },
    {
     "alias": "Server Load (xen-01.mfi.lab)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processors",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "xen-01.mfi.lab" },
      { "condition": "AND", "key": "processor_type", "operator": "=", "value": "hr" }
     ]
    }
   ]
  },
  {
   "title": "XEN-01 (Main Server)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifOutOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/3\\/1|ethernet2\\/3\\/1)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet2/3/1" }
     ]
    },
    {
     "alias": "Upload Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifInOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/3\\/1|ethernet2\\/3\\/1)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet2/3/1" }
     ]
    }
   ]
  },
  {
   "title": "SteamCache Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download (From Valve)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifOutOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/3\\/1|ethernet2\\/3\\/1)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "steamcache.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "eth1" }
     ]
    },
    {
     "alias": "Upload (To Clients)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifOutOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/3\\/1|ethernet2\\/3\\/1)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifOutOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "steamcache.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "eth1" }
     ]
    }
   ]
  },
  {
   "title": "reBOOT WIFI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bps", "label": "Bandwidth" }
   ],
   "targets": [
    {
     "alias": "Download Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "select": [
      [
       { "params": [ "ifOutOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet1/1/1" }
     ]
    },
    {
     "alias": "Upload Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet1/1/1" }
     ]
    },
    {
     "alias": "Connected Devices",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wireless-sensor",
     "select": [
      [
       { "params": [ "sensor" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "ap.mfi.lab" },
      { "condition": "AND", "key": "sensor_class", "operator": "=", "value": "clients" }
     ]
    }
   ]
  },
  {
   "title": "TABLE-01 Switch (ICX7250)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifOutOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/3\\/3|ethernet2\\/3\\/3)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet2/3/1" }
     ]
    },
    {
     "alias": "Upload Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifInOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/3\\/3|ethernet2\\/3\\/3)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet2/3/1" }
     ]
    }
   ]
  },
  {
   "title": "TABLE-02 Switch (ICX7250)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifOutOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/3\\/4|ethernet2\\/3\\/4)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet2/3/1" }
     ]
    },
    {
     "alias": "Upload Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifInOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/3\\/4|ethernet2\\/3\\/4)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet2/3/1" }
     ]
    }
   ]
  },
  {
   "title": "TABLE-03 Switch (ICX7250)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifOutOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/3\\/5|ethernet2\\/3\\/5)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet2/3/1" }
     ]
    },
    {
     "alias": "Upload Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifInOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/3\\/5|ethernet2\\/3\\/5)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet2/3/1" }
     ]
    }
   ]
  },
  {
   "title": "TABLE-04 Switch (ICX7250)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifOutOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/3\\/6|ethernet2\\/3\\/6)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet2/3/1" }
     ]
    },
    {
     "alias": "Upload Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifInOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/3\\/6|ethernet2\\/3\\/6)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet2/3/1" }
     ]
    }
   ]
  },
  {
   "title": "TABLE-05 Switch (ICX6450)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifOutOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/2\\/2|ethernet2\\/2\\/2)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet2/3/1" }
     ]
    },
    {
     "alias": "Upload Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifInOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/2\\/2|ethernet2\\/2\\/2)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet2/3/1" }
     ]
    }
   ]
  },
  {
   "title": "TABLE-06 Switch (ICX6450)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifOutOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/2\\/3|ethernet2\\/2\\/3)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet2/3/1" }
     ]
    },
    {
     "alias": "Upload Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifInOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/2\\/3|ethernet2\\/2\\/3)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet2/3/1" }
     ]
    }
   ]
  },
  {
   "title": "TABLE-07 Switch (ICX6450)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifOutOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/2\\/4|ethernet2\\/2\\/4)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet2/3/1" }
     ]
    },
    {
     "alias": "Upload Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifInOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/2\\/4|ethernet2\\/2\\/4)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet2/3/1" }
     ]
    }
   ]
  },
  {
   "title": "TABLE-08 Switch (FCX)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifOutOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/2\\/5|ethernet2\\/2\\/5)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet2/3/1" }
     ]
    },
    {
     "alias": "Upload Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT sum(\"ifInOctets_rate\") *8 AS \"total\" FROM  \"ports\" WHERE (\"hostname\" = 'lab-core-01-6610.mfi.lab' AND \"ifName\" =~ /(ethernet1\\/2\\/5|ethernet2\\/2\\/5)/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "lab-core-01-6610.mfi.lab" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ethernet2/3/1" }
     ]
    }
   ]
  }
 ]
}